// src/app/layout.js

import RootLayout from "@/app/RootLayout"; // Use alias for components
import "@/styles/globals.css"; // Import global styles
import { getEvents } from "@/app/data";

export const metadata = {
  title: "ResuMax",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  let events = await getEvents();
  return (
    <html
      lang="en"
      className="text-zinc-950 antialiased lg:bg-zinc-100 dark:bg-zinc-900 dark:text-white dark:lg:bg-zinc-950"
    >
      <head>
        <link rel="preconnect" href="https://rsms.me/" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>
      <body>
        <RootLayout events={events}>{children}</RootLayout>
      </body>
    </html>
  );
}
