// src/app/layout.js

import RootLayout from "@/components/RootLayout"; // Use alias for components
import "@/styles/globals.css"; // Import global styles

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return <RootLayout>{children}</RootLayout>;
}
